package com.zato.app.entidades;
// Generated 12/05/2019 05:37:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AptitudOferta generated by hbm2java
 */
@Entity
@Table(name="APTITUD_OFERTA"
    ,schema="SBTEL"
)
public class AptitudOferta  implements java.io.Serializable {


     private BigDecimal pkAptitudOferta;
     private CatalogoAptitud catalogoAptitud;
     private Oferta oferta;

    public AptitudOferta() {
    }

    public AptitudOferta(BigDecimal pkAptitudOferta, CatalogoAptitud catalogoAptitud, Oferta oferta) {
       this.pkAptitudOferta = pkAptitudOferta;
       this.catalogoAptitud = catalogoAptitud;
       this.oferta = oferta;
    }
   
     @Id 

    
    @Column(name="PK_APTITUD_OFERTA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkAptitudOferta() {
        return this.pkAptitudOferta;
    }
    
    public void setPkAptitudOferta(BigDecimal pkAptitudOferta) {
        this.pkAptitudOferta = pkAptitudOferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CATALOGO_APTITUD", nullable=false)
    public CatalogoAptitud getCatalogoAptitud() {
        return this.catalogoAptitud;
    }
    
    public void setCatalogoAptitud(CatalogoAptitud catalogoAptitud) {
        this.catalogoAptitud = catalogoAptitud;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_OFERTA", nullable=false)
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }




}


