package com.zato.app.entidades;
// Generated 24/06/2019 01:24:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CatalogoCategoria generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_CATEGORIA"
)
public class CatalogoCategoria  implements java.io.Serializable {


     private BigDecimal pkCatalogoCategoria;
     private String nombreCatalogoCategoria;
     private Set<CatalogoPuesto> catalogoPuestos = new HashSet<CatalogoPuesto>(0);

    public CatalogoCategoria() {
    }

	
    public CatalogoCategoria(BigDecimal pkCatalogoCategoria, String nombreCatalogoCategoria) {
        this.pkCatalogoCategoria = pkCatalogoCategoria;
        this.nombreCatalogoCategoria = nombreCatalogoCategoria;
    }
    public CatalogoCategoria(BigDecimal pkCatalogoCategoria, String nombreCatalogoCategoria, Set<CatalogoPuesto> catalogoPuestos) {
       this.pkCatalogoCategoria = pkCatalogoCategoria;
       this.nombreCatalogoCategoria = nombreCatalogoCategoria;
       this.catalogoPuestos = catalogoPuestos;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    	
     @SequenceGenerator(sequenceName = "SEQUENCE_CATEGORIA", allocationSize = 1, name = "SEQUENCE_INCREMENT") 
    @Column(name="PK_CATALOGO_CATEGORIA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkCatalogoCategoria() {
        return this.pkCatalogoCategoria;
    }
    
    public void setPkCatalogoCategoria(BigDecimal pkCatalogoCategoria) {
        this.pkCatalogoCategoria = pkCatalogoCategoria;
    }

    
    @Column(name="NOMBRE_CATALOGO_CATEGORIA", nullable=false, length=50)
    public String getNombreCatalogoCategoria() {
        return this.nombreCatalogoCategoria;
    }
    
    public void setNombreCatalogoCategoria(String nombreCatalogoCategoria) {
        this.nombreCatalogoCategoria = nombreCatalogoCategoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoCategoria")
    public Set<CatalogoPuesto> getCatalogoPuestos() {
        return this.catalogoPuestos;
    }
    
    public void setCatalogoPuestos(Set<CatalogoPuesto> catalogoPuestos) {
        this.catalogoPuestos = catalogoPuestos;
    }




}


