package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CatalogoHabilidad generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_HABILIDAD"
)
public class CatalogoHabilidad  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
    private BigDecimal pkHabilidad;
     private CatalogoCategoriaHabilidad catalogoCategoriaHabilidad;
     private String nombreHabilidad;
     private Set<HabilidadOferta> habilidadOfertas = new HashSet<HabilidadOferta>(0);
     private Set<HabilidadesCv> habilidadesCvs = new HashSet<HabilidadesCv>(0);

    public CatalogoHabilidad() {
    }

	
    public CatalogoHabilidad(BigDecimal pkHabilidad, CatalogoCategoriaHabilidad catalogoCategoriaHabilidad, String nombreHabilidad) {
        this.pkHabilidad = pkHabilidad;
        this.catalogoCategoriaHabilidad = catalogoCategoriaHabilidad;
        this.nombreHabilidad = nombreHabilidad;
    }
    public CatalogoHabilidad(BigDecimal pkHabilidad, CatalogoCategoriaHabilidad catalogoCategoriaHabilidad, String nombreHabilidad, Set<HabilidadOferta> habilidadOfertas, Set<HabilidadesCv> habilidadesCvs) {
       this.pkHabilidad = pkHabilidad;
       this.catalogoCategoriaHabilidad = catalogoCategoriaHabilidad;
       this.nombreHabilidad = nombreHabilidad;
       this.habilidadOfertas = habilidadOfertas;
       this.habilidadesCvs = habilidadesCvs;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TIB_HABILIDAD")    
     @SequenceGenerator(sequenceName = "SEQUENCE_HABILIDAD", allocationSize = 1, name = "TIB_HABILIDAD")
    @Column(name="PK_HABILIDAD", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkHabilidad() {
        return this.pkHabilidad;
    }
    
    public void setPkHabilidad(BigDecimal pkHabilidad) {
        this.pkHabilidad = pkHabilidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CATEGORIA_HABILIDAD", nullable=false)
    public CatalogoCategoriaHabilidad getCatalogoCategoriaHabilidad() {
        return this.catalogoCategoriaHabilidad;
    }
    
    public void setCatalogoCategoriaHabilidad(CatalogoCategoriaHabilidad catalogoCategoriaHabilidad) {
        this.catalogoCategoriaHabilidad = catalogoCategoriaHabilidad;
    }

    
    @Column(name="NOMBRE_HABILIDAD", nullable=false, length=100)
    public String getNombreHabilidad() {
        return this.nombreHabilidad;
    }
    
    public void setNombreHabilidad(String nombreHabilidad) {
        this.nombreHabilidad = nombreHabilidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoHabilidad")
    public Set<HabilidadOferta> getHabilidadOfertas() {
        return this.habilidadOfertas;
    }
    
    public void setHabilidadOfertas(Set<HabilidadOferta> habilidadOfertas) {
        this.habilidadOfertas = habilidadOfertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoHabilidad")
    public Set<HabilidadesCv> getHabilidadesCvs() {
        return this.habilidadesCvs;
    }
    
    public void setHabilidadesCvs(Set<HabilidadesCv> habilidadesCvs) {
        this.habilidadesCvs = habilidadesCvs;
    }




}


