package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CatalogoPuesto generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_PUESTO"
)
public class CatalogoPuesto  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
    private BigDecimal pkCatalogoPuesto;
     private CatalogoCategoria catalogoCategoria;
     private String nombreCatalogoPuesto;
     private Set<Oferta> ofertas = new HashSet<Oferta>(0);

    public CatalogoPuesto() {
    }

	
    public CatalogoPuesto(BigDecimal pkCatalogoPuesto, CatalogoCategoria catalogoCategoria, String nombreCatalogoPuesto) {
        this.pkCatalogoPuesto = pkCatalogoPuesto;
        this.catalogoCategoria = catalogoCategoria;
        this.nombreCatalogoPuesto = nombreCatalogoPuesto;
    }
    public CatalogoPuesto(BigDecimal pkCatalogoPuesto, CatalogoCategoria catalogoCategoria, String nombreCatalogoPuesto, Set<Oferta> ofertas) {
       this.pkCatalogoPuesto = pkCatalogoPuesto;
       this.catalogoCategoria = catalogoCategoria;
       this.nombreCatalogoPuesto = nombreCatalogoPuesto;
       this.ofertas = ofertas;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TIB_PUESTO")    
     @SequenceGenerator(sequenceName = "SEQUENCE_PUESTO", allocationSize = 1, name = "TIB_PUESTO") 
    @Column(name="PK_CATALOGO_PUESTO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkCatalogoPuesto() {
        return this.pkCatalogoPuesto;
    }
    
    public void setPkCatalogoPuesto(BigDecimal pkCatalogoPuesto) {
        this.pkCatalogoPuesto = pkCatalogoPuesto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CATALOGO_CATEGORIA", nullable=false)
    public CatalogoCategoria getCatalogoCategoria() {
        return this.catalogoCategoria;
    }
    
    public void setCatalogoCategoria(CatalogoCategoria catalogoCategoria) {
        this.catalogoCategoria = catalogoCategoria;
    }

    
    @Column(name="NOMBRE_CATALOGO_PUESTO", nullable=false, length=50)
    public String getNombreCatalogoPuesto() {
        return this.nombreCatalogoPuesto;
    }
    
    public void setNombreCatalogoPuesto(String nombreCatalogoPuesto) {
        this.nombreCatalogoPuesto = nombreCatalogoPuesto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoPuesto")
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


