package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CatalogoSectorEmpresa generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_SECTOR_EMPRESA"
)
public class CatalogoSectorEmpresa  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
    private BigDecimal pkSector;
     private String nombreSector;
     private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public CatalogoSectorEmpresa() {
    }

	
    public CatalogoSectorEmpresa(BigDecimal pkSector, String nombreSector) {
        this.pkSector = pkSector;
        this.nombreSector = nombreSector;
    }
    public CatalogoSectorEmpresa(BigDecimal pkSector, String nombreSector, Set<ExperienciaLaboral> experienciaLaborals, Set<Empresa> empresas) {
       this.pkSector = pkSector;
       this.nombreSector = nombreSector;
       this.experienciaLaborals = experienciaLaborals;
       this.empresas = empresas;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_INCREMENT", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_SECTOR", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkSector() {
        return this.pkSector;
    }
    
    public void setPkSector(BigDecimal pkSector) {
        this.pkSector = pkSector;
    }

    
    @Column(name="NOMBRE_SECTOR", nullable=false, length=50)
    public String getNombreSector() {
        return this.nombreSector;
    }
    
    public void setNombreSector(String nombreSector) {
        this.nombreSector = nombreSector;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoSectorEmpresa")
    public Set<ExperienciaLaboral> getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set<ExperienciaLaboral> experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoSectorEmpresa")
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


