package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoAptitud generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_APTITUD"
)
public class CatalogoAptitud  implements java.io.Serializable {


     private BigDecimal pkCatalogoAptitud;
     private String nombreAptitud;
     private Set<AptitudOferta> aptitudOfertas = new HashSet<AptitudOferta>(0);
     private Set<AptitudCv> aptitudCvs = new HashSet<AptitudCv>(0);

    public CatalogoAptitud() {
    }

	
    public CatalogoAptitud(BigDecimal pkCatalogoAptitud, String nombreAptitud) {
        this.pkCatalogoAptitud = pkCatalogoAptitud;
        this.nombreAptitud = nombreAptitud;
    }
    public CatalogoAptitud(BigDecimal pkCatalogoAptitud, String nombreAptitud, Set<AptitudOferta> aptitudOfertas, Set<AptitudCv> aptitudCvs) {
       this.pkCatalogoAptitud = pkCatalogoAptitud;
       this.nombreAptitud = nombreAptitud;
       this.aptitudOfertas = aptitudOfertas;
       this.aptitudCvs = aptitudCvs;
    }
   
     @Id 

    
    @Column(name="PK_CATALOGO_APTITUD", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkCatalogoAptitud() {
        return this.pkCatalogoAptitud;
    }
    
    public void setPkCatalogoAptitud(BigDecimal pkCatalogoAptitud) {
        this.pkCatalogoAptitud = pkCatalogoAptitud;
    }

    
    @Column(name="NOMBRE_APTITUD", nullable=false, length=50)
    public String getNombreAptitud() {
        return this.nombreAptitud;
    }
    
    public void setNombreAptitud(String nombreAptitud) {
        this.nombreAptitud = nombreAptitud;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoAptitud")
    public Set<AptitudOferta> getAptitudOfertas() {
        return this.aptitudOfertas;
    }
    
    public void setAptitudOfertas(Set<AptitudOferta> aptitudOfertas) {
        this.aptitudOfertas = aptitudOfertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoAptitud")
    public Set<AptitudCv> getAptitudCvs() {
        return this.aptitudCvs;
    }
    
    public void setAptitudCvs(Set<AptitudCv> aptitudCvs) {
        this.aptitudCvs = aptitudCvs;
    }




}


