package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CatalogoEscrito generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_ESCRITO"
)
public class CatalogoEscrito  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
    private BigDecimal pkCatalogoEscrito;
     private String nombreTipoEscrito;
     private Set<Escrito> escritos = new HashSet<Escrito>(0);

    public CatalogoEscrito() {
    }

	
    public CatalogoEscrito(BigDecimal pkCatalogoEscrito, String nombreTipoEscrito) {
        this.pkCatalogoEscrito = pkCatalogoEscrito;
        this.nombreTipoEscrito = nombreTipoEscrito;
    }
    public CatalogoEscrito(BigDecimal pkCatalogoEscrito, String nombreTipoEscrito, Set<Escrito> escritos) {
       this.pkCatalogoEscrito = pkCatalogoEscrito;
       this.nombreTipoEscrito = nombreTipoEscrito;
       this.escritos = escritos;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT7")
    @SequenceGenerator(sequenceName = "SEQUENCE_CATALOGOESCRITO", allocationSize = 1, name = "SEQUENCE_INCREMENT7")    
    @Column(name="PK_CATALOGO_ESCRITO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkCatalogoEscrito() {
        return this.pkCatalogoEscrito;
    }
    
    public void setPkCatalogoEscrito(BigDecimal pkCatalogoEscrito) {
        this.pkCatalogoEscrito = pkCatalogoEscrito;
    }

    
    @Column(name="NOMBRE_TIPO_ESCRITO", nullable=false, length=100)
    public String getNombreTipoEscrito() {
        return this.nombreTipoEscrito;
    }
    
    public void setNombreTipoEscrito(String nombreTipoEscrito) {
        this.nombreTipoEscrito = nombreTipoEscrito;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoEscrito")
    public Set<Escrito> getEscritos() {
        return this.escritos;
    }
    
    public void setEscritos(Set<Escrito> escritos) {
        this.escritos = escritos;
    }




}


