package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CatalogoGradoAcademico generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_GRADO_ACADEMICO"
)
public class CatalogoGradoAcademico  implements java.io.Serializable {


     private BigDecimal pkGradoAcademico;
     private String nombreGradoAcademico;
     private Set<ConocimientoAcademicos> conocimientoAcademicoses = new HashSet<ConocimientoAcademicos>(0);
     private Set<FormacionAcademica> formacionAcademicas = new HashSet<FormacionAcademica>(0);

    public CatalogoGradoAcademico() {
    }

	
    public CatalogoGradoAcademico(BigDecimal pkGradoAcademico, String nombreGradoAcademico) {
        this.pkGradoAcademico = pkGradoAcademico;
        this.nombreGradoAcademico = nombreGradoAcademico;
    }
    public CatalogoGradoAcademico(BigDecimal pkGradoAcademico, String nombreGradoAcademico, Set<ConocimientoAcademicos> conocimientoAcademicoses, Set<FormacionAcademica> formacionAcademicas) {
       this.pkGradoAcademico = pkGradoAcademico;
       this.nombreGradoAcademico = nombreGradoAcademico;
       this.conocimientoAcademicoses = conocimientoAcademicoses;
       this.formacionAcademicas = formacionAcademicas;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_GRADOACADEMICO", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_GRADO_ACADEMICO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkGradoAcademico() {
        return this.pkGradoAcademico;
    }
    
    public void setPkGradoAcademico(BigDecimal pkGradoAcademico) {
        this.pkGradoAcademico = pkGradoAcademico;
    }

    
    @Column(name="NOMBRE_GRADO_ACADEMICO", nullable=false, length=100)
    public String getNombreGradoAcademico() {
        return this.nombreGradoAcademico;
    }
    
    public void setNombreGradoAcademico(String nombreGradoAcademico) {
        this.nombreGradoAcademico = nombreGradoAcademico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoGradoAcademico")
    public Set<ConocimientoAcademicos> getConocimientoAcademicoses() {
        return this.conocimientoAcademicoses;
    }
    
    public void setConocimientoAcademicoses(Set<ConocimientoAcademicos> conocimientoAcademicoses) {
        this.conocimientoAcademicoses = conocimientoAcademicoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoGradoAcademico")
    public Set<FormacionAcademica> getFormacionAcademicas() {
        return this.formacionAcademicas;
    }
    
    public void setFormacionAcademicas(Set<FormacionAcademica> formacionAcademicas) {
        this.formacionAcademicas = formacionAcademicas;
    }




}


