package com.zato.app.entidades;
// Generated 12/05/2019 05:37:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoGenero generated by hbm2java
 */
@Entity
@Table(name="CATALOGO_GENERO"
    ,schema="SBTEL"
)
public class CatalogoGenero  implements java.io.Serializable {


     private BigDecimal pkGenero;
     private String nombreGenero;
     private Set<Candidato> candidatos = new HashSet<Candidato>(0);

    public CatalogoGenero() {
    }

	
    public CatalogoGenero(BigDecimal pkGenero, String nombreGenero) {
        this.pkGenero = pkGenero;
        this.nombreGenero = nombreGenero;
    }
    public CatalogoGenero(BigDecimal pkGenero, String nombreGenero, Set<Candidato> candidatos) {
       this.pkGenero = pkGenero;
       this.nombreGenero = nombreGenero;
       this.candidatos = candidatos;
    }
   
     @Id 

    
    @Column(name="PK_GENERO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkGenero() {
        return this.pkGenero;
    }
    
    public void setPkGenero(BigDecimal pkGenero) {
        this.pkGenero = pkGenero;
    }

    
    @Column(name="NOMBRE_GENERO", nullable=false, length=50)
    public String getNombreGenero() {
        return this.nombreGenero;
    }
    
    public void setNombreGenero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoGenero")
    public Set<Candidato> getCandidatos() {
        return this.candidatos;
    }
    
    public void setCandidatos(Set<Candidato> candidatos) {
        this.candidatos = candidatos;
    }




}


