package com.zato.app.entidades;
// Generated 12/05/2019 05:37:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CursoCapacitacion generated by hbm2java
 */
@Entity
@Table(name="CURSO_CAPACITACION"
    ,schema="SBTEL"
)
public class CursoCapacitacion  implements java.io.Serializable {


     private BigDecimal pkCursoCapacitacion;
     private Cv cv;
     private String nombreCursoCapacitacion;
     private Date fechaCurso;
     private String nombreInstitutoPonente;
     private String duracion;
     private String lugarCapacitacion;

    public CursoCapacitacion() {
    }

	
    public CursoCapacitacion(BigDecimal pkCursoCapacitacion, Cv cv, String nombreCursoCapacitacion, Date fechaCurso, String nombreInstitutoPonente, String lugarCapacitacion) {
        this.pkCursoCapacitacion = pkCursoCapacitacion;
        this.cv = cv;
        this.nombreCursoCapacitacion = nombreCursoCapacitacion;
        this.fechaCurso = fechaCurso;
        this.nombreInstitutoPonente = nombreInstitutoPonente;
        this.lugarCapacitacion = lugarCapacitacion;
    }
    public CursoCapacitacion(BigDecimal pkCursoCapacitacion, Cv cv, String nombreCursoCapacitacion, Date fechaCurso, String nombreInstitutoPonente, String duracion, String lugarCapacitacion) {
       this.pkCursoCapacitacion = pkCursoCapacitacion;
       this.cv = cv;
       this.nombreCursoCapacitacion = nombreCursoCapacitacion;
       this.fechaCurso = fechaCurso;
       this.nombreInstitutoPonente = nombreInstitutoPonente;
       this.duracion = duracion;
       this.lugarCapacitacion = lugarCapacitacion;
    }
   
     @Id 

    
    @Column(name="PK_CURSO_CAPACITACION", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkCursoCapacitacion() {
        return this.pkCursoCapacitacion;
    }
    
    public void setPkCursoCapacitacion(BigDecimal pkCursoCapacitacion) {
        this.pkCursoCapacitacion = pkCursoCapacitacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CV", nullable=false)
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }

    
    @Column(name="NOMBRE_CURSO_CAPACITACION", nullable=false, length=200)
    public String getNombreCursoCapacitacion() {
        return this.nombreCursoCapacitacion;
    }
    
    public void setNombreCursoCapacitacion(String nombreCursoCapacitacion) {
        this.nombreCursoCapacitacion = nombreCursoCapacitacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CURSO", nullable=false, length=7)
    public Date getFechaCurso() {
        return this.fechaCurso;
    }
    
    public void setFechaCurso(Date fechaCurso) {
        this.fechaCurso = fechaCurso;
    }

    
    @Column(name="NOMBRE_INSTITUTO_PONENTE", nullable=false, length=250)
    public String getNombreInstitutoPonente() {
        return this.nombreInstitutoPonente;
    }
    
    public void setNombreInstitutoPonente(String nombreInstitutoPonente) {
        this.nombreInstitutoPonente = nombreInstitutoPonente;
    }

    
    @Column(name="DURACION", length=100)
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }

    
    @Column(name="LUGAR_CAPACITACION", nullable=false, length=250)
    public String getLugarCapacitacion() {
        return this.lugarCapacitacion;
    }
    
    public void setLugarCapacitacion(String lugarCapacitacion) {
        this.lugarCapacitacion = lugarCapacitacion;
    }




}


