package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cv generated by hbm2java
 */
@Entity
@Table(name="CV"
)
public class Cv  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
    private BigDecimal pkCv;
     private Candidato candidato;
     private String nombreCv;
     private Date fechaRegistro;
     private Date fechaActualizado;
     private Set<Postulacion> postulacions = new HashSet<Postulacion>(0);
     private Set<AptitudCv> aptitudCvs = new HashSet<AptitudCv>(0);
     private Set<HabilidadesCv> habilidadesCvs = new HashSet<HabilidadesCv>(0);
     private Set<Logro> logros = new HashSet<Logro>(0);
     private Set<FormacionAcademica> formacionAcademicas = new HashSet<FormacionAcademica>(0);
     private Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs = new HashSet<HabilidadLinguisticaCv>(0);
     private Set<Referencia> referencias = new HashSet<Referencia>(0);
     private Set<Escrito> escritos = new HashSet<Escrito>(0);
     private Set<CursoCapacitacion> cursoCapacitacions = new HashSet<CursoCapacitacion>(0);
     private Set<Evento> eventos = new HashSet<Evento>(0);
     private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(0);
     private Set<LicenciaCandidato> licenciaCandidatos = new HashSet<LicenciaCandidato>(0);

    public Cv() {
    }

	
    public Cv(BigDecimal pkCv, Candidato candidato, String nombreCv, Date fechaRegistro, Date fechaActualizado) {
        this.pkCv = pkCv;
        this.candidato = candidato;
        this.nombreCv = nombreCv;
        this.fechaRegistro = fechaRegistro;
        this.fechaActualizado = fechaActualizado;
    }
    public Cv(BigDecimal pkCv, Candidato candidato, String nombreCv, Date fechaRegistro, Date fechaActualizado, Set<Postulacion> postulacions, Set<AptitudCv> aptitudCvs, Set<HabilidadesCv> habilidadesCvs, Set<Logro> logros, Set<FormacionAcademica> formacionAcademicas, Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs, Set<Referencia> referencias, Set<Escrito> escritos, Set<CursoCapacitacion> cursoCapacitacions, Set<Evento> eventos, Set<ExperienciaLaboral> experienciaLaborals, Set<LicenciaCandidato> licenciaCandidatos) {
       this.pkCv = pkCv;
       this.candidato = candidato;
       this.nombreCv = nombreCv;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizado = fechaActualizado;
       this.postulacions = postulacions;
       this.aptitudCvs = aptitudCvs;
       this.habilidadesCvs = habilidadesCvs;
       this.logros = logros;
       this.formacionAcademicas = formacionAcademicas;
       this.habilidadLinguisticaCvs = habilidadLinguisticaCvs;
       this.referencias = referencias;
       this.escritos = escritos;
       this.cursoCapacitacions = cursoCapacitacions;
       this.eventos = eventos;
       this.experienciaLaborals = experienciaLaborals;
       this.licenciaCandidatos = licenciaCandidatos;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_CV", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_CV", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkCv() {
        return this.pkCv;
    }
    
    public void setPkCv(BigDecimal pkCv) {
        this.pkCv = pkCv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CANDIDATO", nullable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    
    @Column(name="NOMBRE_CV", nullable=false, length=100)
    public String getNombreCv() {
        return this.nombreCv;
    }
    
    public void setNombreCv(String nombreCv) {
        this.nombreCv = nombreCv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_REGISTRO", nullable=false, length=7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ACTUALIZADO", nullable=false, length=7)
    public Date getFechaActualizado() {
        return this.fechaActualizado;
    }
    
    public void setFechaActualizado(Date fechaActualizado) {
        this.fechaActualizado = fechaActualizado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<Postulacion> getPostulacions() {
        return this.postulacions;
    }
    
    public void setPostulacions(Set<Postulacion> postulacions) {
        this.postulacions = postulacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<AptitudCv> getAptitudCvs() {
        return this.aptitudCvs;
    }
    
    public void setAptitudCvs(Set<AptitudCv> aptitudCvs) {
        this.aptitudCvs = aptitudCvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<HabilidadesCv> getHabilidadesCvs() {
        return this.habilidadesCvs;
    }
    
    public void setHabilidadesCvs(Set<HabilidadesCv> habilidadesCvs) {
        this.habilidadesCvs = habilidadesCvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<Logro> getLogros() {
        return this.logros;
    }
    
    public void setLogros(Set<Logro> logros) {
        this.logros = logros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<FormacionAcademica> getFormacionAcademicas() {
        return this.formacionAcademicas;
    }
    
    public void setFormacionAcademicas(Set<FormacionAcademica> formacionAcademicas) {
        this.formacionAcademicas = formacionAcademicas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<HabilidadLinguisticaCv> getHabilidadLinguisticaCvs() {
        return this.habilidadLinguisticaCvs;
    }
    
    public void setHabilidadLinguisticaCvs(Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs) {
        this.habilidadLinguisticaCvs = habilidadLinguisticaCvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<Referencia> getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(Set<Referencia> referencias) {
        this.referencias = referencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<Escrito> getEscritos() {
        return this.escritos;
    }
    
    public void setEscritos(Set<Escrito> escritos) {
        this.escritos = escritos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<CursoCapacitacion> getCursoCapacitacions() {
        return this.cursoCapacitacions;
    }
    
    public void setCursoCapacitacions(Set<CursoCapacitacion> cursoCapacitacions) {
        this.cursoCapacitacions = cursoCapacitacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<ExperienciaLaboral> getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set<ExperienciaLaboral> experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cv")
    public Set<LicenciaCandidato> getLicenciaCandidatos() {
        return this.licenciaCandidatos;
    }
    
    public void setLicenciaCandidatos(Set<LicenciaCandidato> licenciaCandidatos) {
        this.licenciaCandidatos = licenciaCandidatos;
    }




}


