package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * HabilidadLinguisicaOferta generated by hbm2java
 */
@Entity
@Table(name="HABILIDAD_LINGUISICA_OFERTA"
)
public class HabilidadLinguisicaOferta  implements java.io.Serializable {


     private BigDecimal pkHabilidadLinOf;
     private CatalogoIdioma catalogoIdioma;
     private CatalogoPonderacion catalogoPonderacion;
     private Oferta oferta;
     private BigDecimal pondConversacionOf;
     private BigDecimal pondEscuchaOf;
     private BigDecimal pondEscritoOf;
     private BigDecimal pondLecturaOf;

    public HabilidadLinguisicaOferta() {
    }

    public HabilidadLinguisicaOferta(BigDecimal pkHabilidadLinOf, CatalogoIdioma catalogoIdioma, CatalogoPonderacion catalogoPonderacion, Oferta oferta, BigDecimal pondConversacionOf, BigDecimal pondEscuchaOf, BigDecimal pondEscritoOf, BigDecimal pondLecturaOf) {
       this.pkHabilidadLinOf = pkHabilidadLinOf;
       this.catalogoIdioma = catalogoIdioma;
       this.catalogoPonderacion = catalogoPonderacion;
       this.oferta = oferta;
       this.pondConversacionOf = pondConversacionOf;
       this.pondEscuchaOf = pondEscuchaOf;
       this.pondEscritoOf = pondEscritoOf;
       this.pondLecturaOf = pondLecturaOf;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_HABILIDADLINGOF", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_HABILIDAD_LIN_OF", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkHabilidadLinOf() {
        return this.pkHabilidadLinOf;
    }
    
    public void setPkHabilidadLinOf(BigDecimal pkHabilidadLinOf) {
        this.pkHabilidadLinOf = pkHabilidadLinOf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_IDIOMA", nullable=false)
    public CatalogoIdioma getCatalogoIdioma() {
        return this.catalogoIdioma;
    }
    
    public void setCatalogoIdioma(CatalogoIdioma catalogoIdioma) {
        this.catalogoIdioma = catalogoIdioma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CATALOGO_PONDERACION", nullable=false)
    public CatalogoPonderacion getCatalogoPonderacion() {
        return this.catalogoPonderacion;
    }
    
    public void setCatalogoPonderacion(CatalogoPonderacion catalogoPonderacion) {
        this.catalogoPonderacion = catalogoPonderacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_OFERTA", nullable=false)
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

    
    @Column(name="POND_CONVERSACION_OF", nullable=false, precision=22, scale=0)
    public BigDecimal getPondConversacionOf() {
        return this.pondConversacionOf;
    }
    
    public void setPondConversacionOf(BigDecimal pondConversacionOf) {
        this.pondConversacionOf = pondConversacionOf;
    }

    
    @Column(name="POND_ESCUCHA_OF", nullable=false, precision=22, scale=0)
    public BigDecimal getPondEscuchaOf() {
        return this.pondEscuchaOf;
    }
    
    public void setPondEscuchaOf(BigDecimal pondEscuchaOf) {
        this.pondEscuchaOf = pondEscuchaOf;
    }

    
    @Column(name="POND_ESCRITO_OF", nullable=false, precision=22, scale=0)
    public BigDecimal getPondEscritoOf() {
        return this.pondEscritoOf;
    }
    
    public void setPondEscritoOf(BigDecimal pondEscritoOf) {
        this.pondEscritoOf = pondEscritoOf;
    }

    
    @Column(name="POND_LECTURA_OF", nullable=false, precision=22, scale=0)
    public BigDecimal getPondLecturaOf() {
        return this.pondLecturaOf;
    }
    
    public void setPondLecturaOf(BigDecimal pondLecturaOf) {
        this.pondLecturaOf = pondLecturaOf;
    }




}


