package com.zato.app.entidades;
// Generated 24/06/2019 01:24:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * HabilidadLinguisticaCv generated by hbm2java
 */
@Entity
@Table(name="HABILIDAD_LINGUISTICA_CV"
)
public class HabilidadLinguisticaCv  implements java.io.Serializable {


     private BigDecimal pkHabLingCv;
     private CatalogoIdioma catalogoIdioma;
     private CatalogoPonderacion catalogoPonderacion;
     private Cv cv;
     private BigDecimal pondConversacionCv;
     private BigDecimal pondEscuchaCv;
     private BigDecimal pondEscritoCv;
     private BigDecimal pondLecturaCv;

    public HabilidadLinguisticaCv() {
    }

    public HabilidadLinguisticaCv(BigDecimal pkHabLingCv, CatalogoIdioma catalogoIdioma, CatalogoPonderacion catalogoPonderacion, Cv cv, BigDecimal pondConversacionCv, BigDecimal pondEscuchaCv, BigDecimal pondEscritoCv, BigDecimal pondLecturaCv) {
       this.pkHabLingCv = pkHabLingCv;
       this.catalogoIdioma = catalogoIdioma;
       this.catalogoPonderacion = catalogoPonderacion;
       this.cv = cv;
       this.pondConversacionCv = pondConversacionCv;
       this.pondEscuchaCv = pondEscuchaCv;
       this.pondEscritoCv = pondEscritoCv;
       this.pondLecturaCv = pondLecturaCv;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    	
     @SequenceGenerator(sequenceName = "SEQUENCE_HABILIDADLINGCV", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_HAB_LING_CV", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkHabLingCv() {
        return this.pkHabLingCv;
    }
    
    public void setPkHabLingCv(BigDecimal pkHabLingCv) {
        this.pkHabLingCv = pkHabLingCv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_IDIOMA", nullable=false)
    public CatalogoIdioma getCatalogoIdioma() {
        return this.catalogoIdioma;
    }
    
    public void setCatalogoIdioma(CatalogoIdioma catalogoIdioma) {
        this.catalogoIdioma = catalogoIdioma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CATALOGO_PONDERACION", nullable=true)
    public CatalogoPonderacion getCatalogoPonderacion() {
        return this.catalogoPonderacion;
    }
    
    public void setCatalogoPonderacion(CatalogoPonderacion catalogoPonderacion) {
        this.catalogoPonderacion = catalogoPonderacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CV", nullable=false)
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }

    
    @Column(name="POND_CONVERSACION_CV", nullable=false, precision=22, scale=0)
    public BigDecimal getPondConversacionCv() {
        return this.pondConversacionCv;
    }
    
    public void setPondConversacionCv(BigDecimal pondConversacionCv) {
        this.pondConversacionCv = pondConversacionCv;
    }

    
    @Column(name="POND_ESCUCHA_CV", nullable=false, precision=22, scale=0)
    public BigDecimal getPondEscuchaCv() {
        return this.pondEscuchaCv;
    }
    
    public void setPondEscuchaCv(BigDecimal pondEscuchaCv) {
        this.pondEscuchaCv = pondEscuchaCv;
    }

    
    @Column(name="POND_ESCRITO_CV", nullable=false, precision=22, scale=0)
    public BigDecimal getPondEscritoCv() {
        return this.pondEscritoCv;
    }
    
    public void setPondEscritoCv(BigDecimal pondEscritoCv) {
        this.pondEscritoCv = pondEscritoCv;
    }

    
    @Column(name="POND_LECTURA_CV", nullable=false, precision=22, scale=0)
    public BigDecimal getPondLecturaCv() {
        return this.pondLecturaCv;
    }
    
    public void setPondLecturaCv(BigDecimal pondLecturaCv) {
        this.pondLecturaCv = pondLecturaCv;
    }




}


