package com.zato.app.entidades;
// Generated 24/06/2019 01:24:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Opciones generated by hbm2java
 */
@Entity
@Table(name="OPCIONES"
)
public class Opciones  implements java.io.Serializable {


     private BigDecimal pkOpciones;
     private ItemPrueba itemPrueba;
     private String opcion;
     private double puntajeOpcion;
     private Blob imagenOpcion;

    public Opciones() {
    }

	
    public Opciones(BigDecimal pkOpciones, ItemPrueba itemPrueba, String opcion, double puntajeOpcion) {
        this.pkOpciones = pkOpciones;
        this.itemPrueba = itemPrueba;
        this.opcion = opcion;
        this.puntajeOpcion = puntajeOpcion;
    }
    public Opciones(BigDecimal pkOpciones, ItemPrueba itemPrueba, String opcion, double puntajeOpcion, Blob imagenOpcion) {
       this.pkOpciones = pkOpciones;
       this.itemPrueba = itemPrueba;
       this.opcion = opcion;
       this.puntajeOpcion = puntajeOpcion;
       this.imagenOpcion = imagenOpcion;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    	
     @SequenceGenerator(sequenceName = "SEQUENCE_OPCIONES", allocationSize = 1, name = "SEQUENCE_INCREMENT") 
    
    @Column(name="PK_OPCIONES", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkOpciones() {
        return this.pkOpciones;
    }
    
    public void setPkOpciones(BigDecimal pkOpciones) {
        this.pkOpciones = pkOpciones;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_ITEM", nullable=false)
    public ItemPrueba getItemPrueba() {
        return this.itemPrueba;
    }
    
    public void setItemPrueba(ItemPrueba itemPrueba) {
        this.itemPrueba = itemPrueba;
    }

    
    @Column(name="OPCION", nullable=false, length=250)
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }

    
    @Column(name="PUNTAJE_OPCION", nullable=false, precision=2, scale=0)
    public double getPuntajeOpcion() {
        return this.puntajeOpcion;
    }
    
    public void setPuntajeOpcion(double puntajeOpcion) {
        this.puntajeOpcion = puntajeOpcion;
    }

    
    @Column(name="IMAGEN_OPCION")
    public Blob getImagenOpcion() {
        return this.imagenOpcion;
    }
    
    public void setImagenOpcion(Blob imagenOpcion) {
        this.imagenOpcion = imagenOpcion;
    }




}


