package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="PAIS"
)
public class Pais  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
     private BigDecimal pkPais;
     private String nombrePais;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);
     private Set<Evento> eventos = new HashSet<Evento>(0);

    public Pais() {
    }

	
    public Pais(BigDecimal pkPais, String nombrePais) {
        this.pkPais = pkPais;
        this.nombrePais = nombrePais;
    }
    public Pais(BigDecimal pkPais, String nombrePais, Set<Departamento> departamentos, Set<Evento> eventos) {
       this.pkPais = pkPais;
       this.nombrePais = nombrePais;
       this.departamentos = departamentos;
       this.eventos = eventos;
    }
   
     @Id 
    //LA ANOTACION ES NECESARIA PARA MANEJAR LAS SECUENCIAS DE LOS IDS
    @GeneratedValue(strategy = GenerationType.SEQUENCE)    
    @Column(name="PK_PAIS", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkPais() {
        return this.pkPais;
    }
    
    public void setPkPais(BigDecimal pkPais) {
        this.pkPais = pkPais;
    }

    
    @Column(name="NOMBRE_PAIS", nullable=false, length=50)
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }




}


