package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="PERFIL"
)
public class Perfil  implements java.io.Serializable {


     private BigDecimal pkUsuario;
     private Empresa empresa;
     private Candidato candidato;
     private Rol rol;
     private String usuario;
     private String contrasena;
     private String correoElectronico;
     private BigDecimal tipoPerfil;

    public Perfil() {
    }

	
    public Perfil(BigDecimal pkUsuario, Rol rol, String usuario, String contrasena, String correoElectronico, BigDecimal tipoPerfil) {
        this.pkUsuario = pkUsuario;
        this.rol = rol;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.correoElectronico = correoElectronico;
        this.tipoPerfil = tipoPerfil;
    }
    public Perfil(BigDecimal pkUsuario, Empresa empresa, Candidato candidato, Rol rol, String usuario, String contrasena, String correoElectronico, BigDecimal tipoPerfil) {
       this.pkUsuario = pkUsuario;
       this.empresa = empresa;
       this.candidato = candidato;
       this.rol = rol;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.correoElectronico = correoElectronico;
       this.tipoPerfil = tipoPerfil;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_CANDIDATO", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_USUARIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkUsuario() {
        return this.pkUsuario;
    }
    
    public void setPkUsuario(BigDecimal pkUsuario) {
        this.pkUsuario = pkUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_EMPRESA")
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CANDIDATO")
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_ROL", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="USUARIO", nullable=false, length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="CONTRASENA", nullable=false, length=50)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="CORREO_ELECTRONICO", nullable=false, length=100)
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    
    @Column(name="TIPO_PERFIL", nullable=false, precision=22, scale=0)
    public BigDecimal getTipoPerfil() {
        return this.tipoPerfil;
    }
    
    public void setTipoPerfil(BigDecimal tipoPerfil) {
        this.tipoPerfil = tipoPerfil;
    }




}


