package com.zato.app.entidades;
// Generated 12/05/2019 05:37:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prueba generated by hbm2java
 */
@Entity
@Table(name="PRUEBA"
    ,schema="SBTEL"
)
public class Prueba  implements java.io.Serializable {


     private BigDecimal pkPrueba;
     private CatalogoTipoPrueba catalogoTipoPrueba;
     private Oferta oferta;
     private String nombrePrueba;
     private Set<ItemPrueba> itemPruebas = new HashSet<ItemPrueba>(0);
     private Set<Resultado> resultados = new HashSet<Resultado>(0);

    public Prueba() {
    }

	
    public Prueba(BigDecimal pkPrueba, CatalogoTipoPrueba catalogoTipoPrueba, Oferta oferta, String nombrePrueba) {
        this.pkPrueba = pkPrueba;
        this.catalogoTipoPrueba = catalogoTipoPrueba;
        this.oferta = oferta;
        this.nombrePrueba = nombrePrueba;
    }
    public Prueba(BigDecimal pkPrueba, CatalogoTipoPrueba catalogoTipoPrueba, Oferta oferta, String nombrePrueba, Set<ItemPrueba> itemPruebas, Set<Resultado> resultados) {
       this.pkPrueba = pkPrueba;
       this.catalogoTipoPrueba = catalogoTipoPrueba;
       this.oferta = oferta;
       this.nombrePrueba = nombrePrueba;
       this.itemPruebas = itemPruebas;
       this.resultados = resultados;
    }
   
     @Id 

    
    @Column(name="PK_PRUEBA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkPrueba() {
        return this.pkPrueba;
    }
    
    public void setPkPrueba(BigDecimal pkPrueba) {
        this.pkPrueba = pkPrueba;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CAT_TIPO_PRUEBA", nullable=false)
    public CatalogoTipoPrueba getCatalogoTipoPrueba() {
        return this.catalogoTipoPrueba;
    }
    
    public void setCatalogoTipoPrueba(CatalogoTipoPrueba catalogoTipoPrueba) {
        this.catalogoTipoPrueba = catalogoTipoPrueba;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_OFERTA", nullable=false)
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

    
    @Column(name="NOMBRE_PRUEBA", nullable=false, length=100)
    public String getNombrePrueba() {
        return this.nombrePrueba;
    }
    
    public void setNombrePrueba(String nombrePrueba) {
        this.nombrePrueba = nombrePrueba;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prueba")
    public Set<ItemPrueba> getItemPruebas() {
        return this.itemPruebas;
    }
    
    public void setItemPruebas(Set<ItemPrueba> itemPruebas) {
        this.itemPruebas = itemPruebas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prueba")
    public Set<Resultado> getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Set<Resultado> resultados) {
        this.resultados = resultados;
    }




}


