package com.zato.app.entidades;
// Generated 24/06/2019 01:24:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PruebaOferta generated by hbm2java
 */
@Entity
@Table(name="PRUEBA_OFERTA"
)
public class PruebaOferta  implements java.io.Serializable {


     private BigDecimal pkPruebaOferta;
     private Oferta oferta;
     private Prueba prueba;
     private Set<Resultado> resultados = new HashSet<Resultado>(0);

    public PruebaOferta() {
    }

	
    public PruebaOferta(BigDecimal pkPruebaOferta, Oferta oferta, Prueba prueba) {
        this.pkPruebaOferta = pkPruebaOferta;
        this.oferta = oferta;
        this.prueba = prueba;
    }
    public PruebaOferta(BigDecimal pkPruebaOferta, Oferta oferta, Prueba prueba, Set<Resultado> resultados) {
       this.pkPruebaOferta = pkPruebaOferta;
       this.oferta = oferta;
       this.prueba = prueba;
       this.resultados = resultados;
    }
   
     @Id 

    
    @Column(name="PK_PRUEBA_OFERTA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkPruebaOferta() {
        return this.pkPruebaOferta;
    }
    
    public void setPkPruebaOferta(BigDecimal pkPruebaOferta) {
        this.pkPruebaOferta = pkPruebaOferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_OFERTA", nullable=false)
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_PRUEBA", nullable=false)
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pruebaOferta")
    public Set<Resultado> getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Set<Resultado> resultados) {
        this.resultados = resultados;
    }




}


