package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PruebaOferta generated by hbm2java
 */
@Entity
@Table(name="PRUEBA_OFERTA"
)
public class PruebaOferta  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
    private BigDecimal pkPruebaOferta;
     private Oferta oferta;
     private Prueba prueba;

    public PruebaOferta() {
    }

    public PruebaOferta(BigDecimal pkPruebaOferta, Oferta oferta, Prueba prueba) {
       this.pkPruebaOferta = pkPruebaOferta;
       this.oferta = oferta;
       this.prueba = prueba;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT39")    
     @SequenceGenerator(sequenceName = "SEQUENCE_OFERTA_PRUEBA", allocationSize = 1, name = "SEQUENCE_INCREMENT39") 
    @Column(name="PK_PRUEBA_OFERTA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkPruebaOferta() {
        return this.pkPruebaOferta;
    }
    
    public void setPkPruebaOferta(BigDecimal pkPruebaOferta) {
        this.pkPruebaOferta = pkPruebaOferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_OFERTA", nullable=false)
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_PRUEBA", nullable=false)
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }




}


