package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Referencia generated by hbm2java
 */
@Entity
@Table(name="REFERENCIA"
)
public class Referencia  implements java.io.Serializable {


     private BigDecimal pkReferencia;
     private CatalogoTipoReferencia catalogoTipoReferencia;
     private Cv cv;
     private String nombreReferencia;
     private long telefonoReferencia;
     private String empresaReferencia;
     private Blob recomendacionPdf;

    public Referencia() {
    }

	
    public Referencia(BigDecimal pkReferencia, CatalogoTipoReferencia catalogoTipoReferencia, Cv cv, String nombreReferencia, long telefonoReferencia) {
        this.pkReferencia = pkReferencia;
        this.catalogoTipoReferencia = catalogoTipoReferencia;
        this.cv = cv;
        this.nombreReferencia = nombreReferencia;
        this.telefonoReferencia = telefonoReferencia;
    }
    public Referencia(BigDecimal pkReferencia, CatalogoTipoReferencia catalogoTipoReferencia, Cv cv, String nombreReferencia, long telefonoReferencia, String empresaReferencia, Blob recomendacionPdf) {
       this.pkReferencia = pkReferencia;
       this.catalogoTipoReferencia = catalogoTipoReferencia;
       this.cv = cv;
       this.nombreReferencia = nombreReferencia;
       this.telefonoReferencia = telefonoReferencia;
       this.empresaReferencia = empresaReferencia;
       this.recomendacionPdf = recomendacionPdf;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_CANDIDATO", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    
    @Column(name="PK_REFERENCIA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkReferencia() {
        return this.pkReferencia;
    }
    
    public void setPkReferencia(BigDecimal pkReferencia) {
        this.pkReferencia = pkReferencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_TIPO_REFERENCIA", nullable=false)
    public CatalogoTipoReferencia getCatalogoTipoReferencia() {
        return this.catalogoTipoReferencia;
    }
    
    public void setCatalogoTipoReferencia(CatalogoTipoReferencia catalogoTipoReferencia) {
        this.catalogoTipoReferencia = catalogoTipoReferencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_CV", nullable=false)
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }

    
    @Column(name="NOMBRE_REFERENCIA", nullable=false, length=100)
    public String getNombreReferencia() {
        return this.nombreReferencia;
    }
    
    public void setNombreReferencia(String nombreReferencia) {
        this.nombreReferencia = nombreReferencia;
    }

    
    @Column(name="TELEFONO_REFERENCIA", nullable=false, precision=14, scale=0)
    public long getTelefonoReferencia() {
        return this.telefonoReferencia;
    }
    
    public void setTelefonoReferencia(long telefonoReferencia) {
        this.telefonoReferencia = telefonoReferencia;
    }

    
    @Column(name="EMPRESA_REFERENCIA", length=250)
    public String getEmpresaReferencia() {
        return this.empresaReferencia;
    }
    
    public void setEmpresaReferencia(String empresaReferencia) {
        this.empresaReferencia = empresaReferencia;
    }

    
    @Column(name="RECOMENDACION_PDF")
    public Blob getRecomendacionPdf() {
        return this.recomendacionPdf;
    }
    
    public void setRecomendacionPdf(Blob recomendacionPdf) {
        this.recomendacionPdf = recomendacionPdf;
    }




}


