package com.zato.app.entidades;
// Generated 12/06/2019 08:39:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Resultado generated by hbm2java
 */
@Entity
@Table(name="RESULTADO"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK_PRUEBA") 
)
public class Resultado  implements java.io.Serializable {


     private static final long serialVersionUID = 1L;
    private BigDecimal pkResultado;
     private Postulacion postulacion;
     private Prueba prueba;
     private String resultado;

    public Resultado() {
    }

	
    public Resultado(BigDecimal pkResultado, Prueba prueba, String resultado) {
        this.pkResultado = pkResultado;
        this.prueba = prueba;
        this.resultado = resultado;
    }
    public Resultado(BigDecimal pkResultado, Postulacion postulacion, Prueba prueba, String resultado) {
       this.pkResultado = pkResultado;
       this.postulacion = postulacion;
       this.prueba = prueba;
       this.resultado = resultado;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_RESULTADO", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_RESULTADO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkResultado() {
        return this.pkResultado;
    }
    
    public void setPkResultado(BigDecimal pkResultado) {
        this.pkResultado = pkResultado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_POSTULACION")
    public Postulacion getPostulacion() {
        return this.postulacion;
    }
    
    public void setPostulacion(Postulacion postulacion) {
        this.postulacion = postulacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_PRUEBA", unique=true, nullable=false)
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }

    
    @Column(name="RESULTADO", nullable=false, length=25)
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


