package com.zato.app.entidades;
// Generated 24/06/2019 01:24:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Resultado generated by hbm2java
 */
@Entity
@Table(name="RESULTADO"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK_PRUEBA_OFERTA") 
)
public class Resultado  implements java.io.Serializable {


     private BigDecimal pkResultado;
     private Postulacion postulacion;
     private PruebaOferta pruebaOferta;
     private String resultado;

    public Resultado() {
    }

	
    public Resultado(BigDecimal pkResultado, Postulacion postulacion, PruebaOferta pruebaOferta) {
        this.pkResultado = pkResultado;
        this.postulacion = postulacion;
        this.pruebaOferta = pruebaOferta;
    }
    public Resultado(BigDecimal pkResultado, Postulacion postulacion, PruebaOferta pruebaOferta, String resultado) {
       this.pkResultado = pkResultado;
       this.postulacion = postulacion;
       this.pruebaOferta = pruebaOferta;
       this.resultado = resultado;
    }
   
     @Id 

    
    @Column(name="PK_RESULTADO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkResultado() {
        return this.pkResultado;
    }
    
    public void setPkResultado(BigDecimal pkResultado) {
        this.pkResultado = pkResultado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_POSTULACION", nullable=false)
    public Postulacion getPostulacion() {
        return this.postulacion;
    }
    
    public void setPostulacion(Postulacion postulacion) {
        this.postulacion = postulacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_PRUEBA_OFERTA", unique=true, nullable=false)
    public PruebaOferta getPruebaOferta() {
        return this.pruebaOferta;
    }
    
    public void setPruebaOferta(PruebaOferta pruebaOferta) {
        this.pruebaOferta = pruebaOferta;
    }

    
    @Column(name="RESULTADO", length=25)
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


