package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Resultado generated by hbm2java
 */
@Entity
@Table(name="RESULTADO"
)
public class Resultado  implements java.io.Serializable {


     private BigDecimal pkResultado;
     private Prueba prueba;
     private String resultado;

    public Resultado() {
    }

    public Resultado(BigDecimal pkResultado, Prueba prueba, String resultado) {
       this.pkResultado = pkResultado;
       this.prueba = prueba;
       this.resultado = resultado;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_CANDIDATO", allocationSize = 1, name = "SEQUENCE_INCREMENT")
    @Column(name="PK_RESULTADO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkResultado() {
        return this.pkResultado;
    }
    
    public void setPkResultado(BigDecimal pkResultado) {
        this.pkResultado = pkResultado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_PRUEBA", nullable=false)
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }

    
    @Column(name="RESULTADO", nullable=false, length=25)
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


