package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="ROL"
)
public class Rol  implements java.io.Serializable {


     private BigDecimal pkRol;
     private String nombreRol;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);
     private Set<RolSubmenu> rolSubmenus = new HashSet<RolSubmenu>(0);

    public Rol() {
    }

	
    public Rol(BigDecimal pkRol, String nombreRol) {
        this.pkRol = pkRol;
        this.nombreRol = nombreRol;
    }
    public Rol(BigDecimal pkRol, String nombreRol, Set<Perfil> perfils, Set<RolSubmenu> rolSubmenus) {
       this.pkRol = pkRol;
       this.nombreRol = nombreRol;
       this.perfils = perfils;
       this.rolSubmenus = rolSubmenus;
    }
   
     @Id 

    
    @Column(name="PK_ROL", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkRol() {
        return this.pkRol;
    }
    
    public void setPkRol(BigDecimal pkRol) {
        this.pkRol = pkRol;
    }

    
    @Column(name="NOMBRE_ROL", nullable=false, length=50)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<RolSubmenu> getRolSubmenus() {
        return this.rolSubmenus;
    }
    
    public void setRolSubmenus(Set<RolSubmenu> rolSubmenus) {
        this.rolSubmenus = rolSubmenus;
    }




}


