package com.zato.app.entidades;
// Generated 18/05/2019 06:12:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Submenu generated by hbm2java
 */
@Entity
@Table(name="SUBMENU"
)
public class Submenu  implements java.io.Serializable {


     private BigDecimal pkSubmenu;
     private Menu menu;
     private String submenu;
     private String orden;
     private Set<RolSubmenu> rolSubmenus = new HashSet<RolSubmenu>(0);

    public Submenu() {
    }

	
    public Submenu(BigDecimal pkSubmenu, String submenu, String orden) {
        this.pkSubmenu = pkSubmenu;
        this.submenu = submenu;
        this.orden = orden;
    }
    public Submenu(BigDecimal pkSubmenu, Menu menu, String submenu, String orden, Set<RolSubmenu> rolSubmenus) {
       this.pkSubmenu = pkSubmenu;
       this.menu = menu;
       this.submenu = submenu;
       this.orden = orden;
       this.rolSubmenus = rolSubmenus;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQUENCE_INCREMENT")    
     @SequenceGenerator(sequenceName = "SEQUENCE_CANDIDATO", allocationSize = 1, name = "SEQUENCE_INCREMENT")    
    @Column(name="PK_SUBMENU", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPkSubmenu() {
        return this.pkSubmenu;
    }
    
    public void setPkSubmenu(BigDecimal pkSubmenu) {
        this.pkSubmenu = pkSubmenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_MENU")
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    
    @Column(name="SUBMENU", nullable=false, length=100)
    public String getSubmenu() {
        return this.submenu;
    }
    
    public void setSubmenu(String submenu) {
        this.submenu = submenu;
    }

    
    @Column(name="ORDEN", nullable=false, length=100)
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="submenu")
    public Set<RolSubmenu> getRolSubmenus() {
        return this.rolSubmenus;
    }
    
    public void setRolSubmenus(Set<RolSubmenu> rolSubmenus) {
        this.rolSubmenus = rolSubmenus;
    }




}


