INSERT INTO CATALOGO_APTITUD VALUES(1,'Proactividad');
INSERT INTO CATALOGO_APTITUD VALUES(2,'Trabajo en equipo');
INSERT INTO CATALOGO_APTITUD VALUES(3,'Disciplina');
INSERT INTO CATALOGO_APTITUD VALUES(4,'Adaptacion');
INSERT INTO CATALOGO_APTITUD VALUES(5,'Creatividad');

INSERT INTO CATALOGO_CATEGORIA VALUES(1,'Ventas');
INSERT INTO CATALOGO_CATEGORIA VALUES(2,'Logistica');
INSERT INTO CATALOGO_CATEGORIA VALUES(3,'Transporte');
INSERT INTO CATALOGO_CATEGORIA VALUES(4,'Informatica');
INSERT INTO CATALOGO_CATEGORIA VALUES(5,'Telecomunicaciones');
INSERT INTO CATALOGO_CATEGORIA VALUES(6,'Administracion');
INSERT INTO CATALOGO_CATEGORIA VALUES(7,'Contabilidad');
INSERT INTO CATALOGO_CATEGORIA VALUES(8,'Atencion al cliente');
INSERT INTO CATALOGO_CATEGORIA VALUES(9,'Hoteleria y turismo');
INSERT INTO CATALOGO_CATEGORIA VALUES(10,'Ingenieria');
INSERT INTO CATALOGO_CATEGORIA VALUES(11,'Recursos Humanos');

INSERT INTO CATALOGO_CATEGORIA_HABILIDAD VALUES(1,'Autodidacta');
INSERT INTO CATALOGO_CATEGORIA_HABILIDAD VALUES(2,'Atención a los detalles');
INSERT INTO CATALOGO_CATEGORIA_HABILIDAD VALUES(3,'Curiosidad');
INSERT INTO CATALOGO_CATEGORIA_HABILIDAD VALUES(4,'Adaptabilidad');
INSERT INTO CATALOGO_CATEGORIA_HABILIDAD VALUES(5,'Comunicación efectiva');

INSERT INTO CATALOGO_ESCRITO VALUES(1,'Cientifico');
INSERT INTO CATALOGO_ESCRITO VALUES(2,'Periodisctico');
INSERT INTO CATALOGO_ESCRITO VALUES(3,'Didactico');
INSERT INTO CATALOGO_ESCRITO VALUES(4,'Ensayo');
INSERT INTO CATALOGO_ESCRITO VALUES(5,'Explicativo');
INSERT INTO CATALOGO_ESCRITO VALUES(6,'Filosofico');
INSERT INTO CATALOGO_ESCRITO VALUES(7,'Informativo');
INSERT INTO CATALOGO_ESCRITO VALUES(8,'Instructivo');
INSERT INTO CATALOGO_ESCRITO VALUES(9,'Literario');
INSERT INTO CATALOGO_ESCRITO VALUES(10,'Matematico');
INSERT INTO CATALOGO_ESCRITO VALUES(11,'Medico');

INSERT INTO CATALOGO_GENERO VALUES(1,'Hombre');
INSERT INTO CATALOGO_GENERO VALUES(2,'Mujer');

INSERT INTO CATALOGO_GRADO_ACADEMICO VALUES(1,'Bachiller');
INSERT INTO CATALOGO_GRADO_ACADEMICO VALUES(2,'Tecnico');
INSERT INTO CATALOGO_GRADO_ACADEMICO VALUES(3,'Licenciatura');
INSERT INTO CATALOGO_GRADO_ACADEMICO VALUES(4,'Doctorado');
INSERT INTO CATALOGO_GRADO_ACADEMICO VALUES(5,'Maestria');
INSERT INTO CATALOGO_GRADO_ACADEMICO VALUES(6,'Posgrao');

INSERT INTO CATALOGO_HABILIDAD VALUES(1,'Innovación');
INSERT INTO CATALOGO_HABILIDAD VALUES(2,'Análisis, Síntesis y Crítica');
INSERT INTO CATALOGO_HABILIDAD VALUES(3,'Organización y Planificación');
INSERT INTO CATALOGO_HABILIDAD VALUES(4,'Habilidades de Comunicación');
INSERT INTO CATALOGO_HABILIDAD VALUES(5,'Responsabilidad y Perseverancia');
INSERT INTO CATALOGO_HABILIDAD VALUES(6,'Toma de Decisiones');
INSERT INTO CATALOGO_HABILIDAD VALUES(7,'Orientación a Clientes');
INSERT INTO CATALOGO_HABILIDAD VALUES(8,'Trabajo en Equipo y Cooperación');
INSERT INTO CATALOGO_HABILIDAD VALUES(9,'Capacidad de Aprendizaje y Adaptación');
INSERT INTO CATALOGO_HABILIDAD VALUES(10,'Flexibilidad y Orientación al Cambio');
INSERT INTO CATALOGO_HABILIDAD VALUES(11,'Motivación por el Logro');

INSERT INTO CATALOGO_IDIOMA VALUES(1,'Chino');
INSERT INTO CATALOGO_IDIOMA VALUES(2,'Español');
INSERT INTO CATALOGO_IDIOMA VALUES(3,'Ingles');
INSERT INTO CATALOGO_IDIOMA VALUES(4,'Arabe');
INSERT INTO CATALOGO_IDIOMA VALUES(5,'Portugues');
INSERT INTO CATALOGO_IDIOMA VALUES(6,'Ruso');
INSERT INTO CATALOGO_IDIOMA VALUES(7,'Japones');

INSERT INTO CATALOGO_LICENCIA VALUES(1,'Motocicleta');
INSERT INTO CATALOGO_LICENCIA VALUES(2,'Particular');
INSERT INTO CATALOGO_LICENCIA VALUES(3,'Liviana');
INSERT INTO CATALOGO_LICENCIA VALUES(4,'Pesada');
INSERT INTO CATALOGO_LICENCIA VALUES(5,'Pesada-T');

INSERT INTO CATALOGO_PONDERACION VALUES(1,'0.2');
INSERT INTO CATALOGO_PONDERACION VALUES(2,'0.1');
INSERT INTO CATALOGO_PONDERACION VALUES(3,'0.05');

INSERT INTO CATALOGO_PUESTO VALUES(1,'Analista programador');
INSERT INTO CATALOGO_PUESTO VALUES(2,'Agente de seguridad');
INSERT INTO CATALOGO_PUESTO VALUES(3,'Ejecutivo de ventas');
INSERT INTO CATALOGO_PUESTO VALUES(4,'Analisa de mercadeo');
INSERT INTO CATALOGO_PUESTO VALUES(5,'Gerente de sucursal');

INSERT INTO CATALOGO_SECTOR_EMPRESA VALUES(1,'Manofactura');
INSERT INTO CATALOGO_SECTOR_EMPRESA VALUES(2,'Industrial');
INSERT INTO CATALOGO_SECTOR_EMPRESA VALUES(3,'Textil');
INSERT INTO CATALOGO_SECTOR_EMPRESA VALUES(4,'Informatica');
INSERT INTO CATALOGO_SECTOR_EMPRESA VALUES(5,'Servicos');

INSERT INTO CATALOGO_TIPO_EMPRESA VALUES(1,'Grande');
INSERT INTO CATALOGO_TIPO_EMPRESA VALUES(2,'Mediana');
INSERT INTO CATALOGO_TIPO_EMPRESA VALUES(3,'Pequeña');
INSERT INTO CATALOGO_TIPO_EMPRESA VALUES(4,'Microempresa');

INSERT INTO CATALOGO_TIPO_PRUEBA VALUES(1,'Psicologica');
INSERT INTO CATALOGO_TIPO_PRUEBA VALUES(2,'Aptitud');
INSERT INTO CATALOGO_TIPO_PRUEBA VALUES(3,'Ingles');
INSERT INTO CATALOGO_TIPO_PRUEBA VALUES(4,'informatica');

INSERT INTO CATALOGO_TIPO_REFERENCIA  VALUES(1,'Personal');
INSERT INTO CATALOGO_TIPO_REFERENCIA  VALUES(2,'Laboral');

INSERT INTO DEPARTAMENTO VALUES(1,'Ahuachapán');
INSERT INTO DEPARTAMENTO VALUES(2,'Cabañas');
INSERT INTO DEPARTAMENTO VALUES(3,'Chalatenango');
INSERT INTO DEPARTAMENTO VALUES(4,'Cuscatlán');
INSERT INTO DEPARTAMENTO VALUES(5,'Morazán');
INSERT INTO DEPARTAMENTO VALUES(6,'La Libertad');
INSERT INTO DEPARTAMENTO VALUES(7,'La Paz');
INSERT INTO DEPARTAMENTO VALUES(8,'La Unión');
INSERT INTO DEPARTAMENTO VALUES(9,'San Miguel');
INSERT INTO DEPARTAMENTO VALUES(10,'San Salvador');
INSERT INTO DEPARTAMENTO VALUES(11,'San Vicente');

INSERT INTO PAIS VALUES(1,'El Salvador');
INSERT INTO PAIS VALUES(2,'Guatemala');

INSERT INTO MUNICIPIO VALUES(1,'Apopa');
INSERT INTO MUNICIPIO VALUES(2,'Ayutuxtepeque');
INSERT INTO MUNICIPIO VALUES(3,'Delgado');
INSERT INTO MUNICIPIO VALUES(4,'Cuscatancingo');
INSERT INTO MUNICIPIO VALUES(5,'El Paisnal');
INSERT INTO MUNICIPIO VALUES(6,'Guazapa');
INSERT INTO MUNICIPIO VALUES(7,'Ilopango');
INSERT INTO MUNICIPIO VALUES(8,'Mejicanos');
INSERT INTO MUNICIPIO VALUES(9,'Nejapa');
INSERT INTO MUNICIPIO VALUES(10,'Panchimalco');
INSERT INTO MUNICIPIO VALUES(11,'Rosario de Mora');


































