
INSERT INTO PAIS (PK_PAIS, NOMBRE_PAIS) VALUES ('1', 'El Salvador');
INSERT INTO PAIS (PK_PAIS, NOMBRE_PAIS) VALUES ('2', 'Guatemala');
INSERT INTO PAIS (PK_PAIS, NOMBRE_PAIS) VALUES ('3', 'Honduras');

--ROLES--
INSERT INTO ROL (PK_ROL, NOMBRE_ROL) VALUES ('1', 'Candidato');
INSERT INTO ROL (PK_ROL, NOMBRE_ROL) VALUES ('2', 'Empresa');
INSERT INTO ROL (PK_ROL, NOMBRE_ROL) VALUES ('3', 'Administrador');

-- GENERO--
INSERT INTO CATALOGO_GENERO (PK_GENERO, NOMBRE_GENERO) VALUES ('1', 'Masculino');

-- DEPARTAMENTO--
INSERT INTO DEPARTAMENTO (PK_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, PK_PAIS) VALUES ('1', 'La Libertad', '1');

--MUNICIPIO--
INSERT INTO MUNICIPIO (PK_MUNICIPIO, NOMBRE_MUNICIPIO,PK_DEPARTAMENTO) VALUES ('1', 'Santa Tecla', '1');

-- CANDIDATO--
INSERT INTO CANDIDATO (PK_CANDIDATO, NOMBRE_CANDIDATO, APELLIDO_CANDIDATO,CELULAR, DIRECCION, DUI,FECHA_NACIMIENTO,NACIONALIDAD, NIT,NUP, PASAPORTE,TELEFONO,TWITTER,FACEBOOK,PK_GENERO,PK_MUNICIPIO,FOTO_CANDIDATO) 
VALUES ('1', 'JUAN','LOPEZ','55555555','Santa tecla','12345678','13/06/19','Salvadoreña','1234567890','0987654321','0987654321','123456','','','1','1','');